
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hazim Hanif
 */
public class Hangman extends javax.swing.JFrame {

    /**
     * Creates new form Hangman
     */
    public void work() throws FileNotFoundException{
        Words w = new Words();
        Hangman h =new Hangman();
        w.getphrase();
        System.out.println(w.p);
        w.getdesc();
        System.out.println(w.d);
        w.getlength();
        System.out.println(w.length);
        w.getspace();
        System.out.println(w.guess);

    }
    
    public Hangman() {
        initComponents();
        
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hangman The Game");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pole.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBounds(250, 50, 550, 400);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel3.setText(" ");
        jLabel3.setBounds(60, 510, 660, 26);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 36)); // NOI18N
        jLabel2.setLabelFor(jLabel2);
        jLabel2.setText(" ");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setOpaque(true);
        jLabel2.setBounds(50, 450, 690, 56);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jLabel5.setText("Alphabet");
        jLabel5.setBounds(10, 0, 90, 30);
        jLayeredPane2.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jLabel4.setText("Used");
        jLabel4.setBounds(20, 20, 70, 30);
        jLayeredPane2.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText(":");
        jLabel6.setBounds(100, 0, 10, 50);
        jLayeredPane2.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText(" ");
        jLabel7.setBounds(120, 10, 670, 30);
        jLayeredPane2.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(0, 0, 800, 590);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-816)/2, (screenSize.height-629)/2, 816, 629);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        revalidate();
        repaint();
        Edit_admin ea = new Edit_admin();
        Words w = new Words();
        w.c = Character.toLowerCase(evt.getKeyChar());
        System.out.println(w.c);
        w.compare();
        
        w.used = w.used+("  ")+Character.toString(Character.toUpperCase(w.c));
        this.jLabel7.setText(w.used);
        
        this.jLabel2.setText(w.guess);
        
        if(w.guess.equalsIgnoreCase(w.p))
        {
            
            if(w.error<=3)
                w.score = w.score+30;

            System.out.println("You Win");
            win ww = new win();
            
            int winning=0 ;
            
         Scanner sc = null;
            try {
            sc = new Scanner(new File("/Hangman The Game/player/"+ea.uunew+"/win.txt")); 
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Edit_player.class.getName()).log(Level.SEVERE, null, ex);
        }
          winning = Integer.parseInt(sc.nextLine());
           sc.close();
         
         
            PrintWriter p = null;
            try {
                p = new PrintWriter(new FileOutputStream("/Hangman The Game/player/"+ea.uunew+"/win.txt"));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Hangman.class.getName()).log(Level.SEVERE, null, ex);
            }
            p.println(Integer.toString(winning+1));
            p.close();
            
             try {
            w.printscore();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Hangman.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            ww.setVisible(true);
            dispose();
        }
            
         
        switch(w.error)
       {
           case 1 :  
                     jLabel1.setIcon(new javax.swing.ImageIcon("\\Hangman The Game\\pic\\headpic.jpg"));
                     jLabel1.setIcon(new javax.swing.ImageIcon("\\Hangman The Game\\pic\\head.gif"));
                     break;
                    
                    
           case 2 : jLabel1.setIcon(new javax.swing.ImageIcon("\\Hangman The Game\\pic\\bodypic.jpg"));
                    jLabel1.setIcon(new javax.swing.ImageIcon("\\Hangman The Game\\pic\\body.gif"));
                    break;
           
           case 3 : jLabel1.setIcon(new javax.swing.ImageIcon("\\Hangman The Game\\pic\\rHandpic.jpg"));
                    jLabel1.setIcon(new javax.swing.ImageIcon("\\Hangman The Game\\pic\\rHand.gif"));
                    break;
           
           case 4 : jLabel1.setIcon(new javax.swing.ImageIcon("\\Hangman The Game\\pic\\lHandpic.jpg"));
                    jLabel1.setIcon(new javax.swing.ImageIcon("\\Hangman The Game\\pic\\lHand.gif"));
                    break;
               
           case 5 : jLabel1.setIcon(new javax.swing.ImageIcon("\\Hangman The Game\\pic\\rLegpic.jpg"));
                    jLabel1.setIcon(new javax.swing.ImageIcon("\\Hangman The Game\\pic\\rLeg.gif"));
                    break;
               
           case 6 : jLabel1.setIcon(new javax.swing.ImageIcon("\\Hangman The Game\\pic\\lLegpic.jpg"));
                    jLabel1.setIcon(new javax.swing.ImageIcon("\\Hangman The Game\\pic\\lLeg.gif"));
                    System.out.println("You Lose");
                    this.jLabel2.setText(w.p);
                    lose l = new lose();
                    
                    int losing=0 ;
            
         Scanner sc = null;
            try {
            sc = new Scanner(new File("/Hangman The Game/player/"+ea.uunew+"/lose.txt")); 
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Edit_player.class.getName()).log(Level.SEVERE, null, ex);
        }
         losing = Integer.parseInt(sc.nextLine());
           sc.close();
         
         
            PrintWriter p = null;
            try {
                p = new PrintWriter(new FileOutputStream("/Hangman The Game/player/"+ea.uunew+"/lose.txt"));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Hangman.class.getName()).log(Level.SEVERE, null, ex);
            }
            p.println(Integer.toString(losing+1));
            p.close();
       
            try {
            w.printscore();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Hangman.class.getName()).log(Level.SEVERE, null, ex);
        }
                    l.setVisible(true);
                    dispose();
                    break;
           
           default :      
       }
       
        
        
    }//GEN-LAST:event_formKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        revalidate();
        repaint();
        
        Words w = new Words();
        
        w.score=0;
        w.deduct=0;
        w.error=0;
        w.correct=0;
        w.used="";
        
        jLabel1.setIcon(new javax.swing.ImageIcon("\\Hangman The Game\\pic\\pole.gif"));
            Hangman h =new Hangman();
        try {
            h.work();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Hangman.class.getName()).log(Level.SEVERE, null, ex);
        }
       
  
        this.jLabel2.setText(w.guess);
        this.jLabel3.setText(w.d);
        
    }//GEN-LAST:event_formWindowOpened

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hangman().setVisible(true);
            }
        });
        
     
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
